# Generated by Django 5.0.3 on 2024-05-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cat_breed",
            field=models.TextField(default="None"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="link_to_pfp",
            field=models.TextField(default="https://imgur.com/a/3jIMzB5"),
        ),
    ]
