# Generated by Django 5.0.3 on 2024-05-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_userprofile_cat_breed_userprofile_link_to_pfp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(default="None"),
        ),
    ]
