# Generated by Django 5.0.3 on 2024-05-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_userprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="link_to_pfp",
            field=models.TextField(default="https://i.imgur.com/Fq5xOFO.png"),
        ),
    ]
