# Generated by Django 5.0.4 on 2024-05-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_post_likes_post_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="core.userprofile"
            ),
        ),
    ]
